### ISSUE TITLE
Benchmarks test segfaults on blueos

### ISSUE THREAD

**Issue by rcarson3** [LLNL/CARE#84]
Building CARE with commit 4fded0bc3d0f755a051b24f5caefc2912f19ef54 on rzansel with the blueos config file provided in the repo resulted in a segfault on the Benchmarks test for both a debug and release build.

If it helps here's the exact cmake invocation I ran within the build directory as well:

```
cmake ../ -C ../configs/lc/blueos/nvcc10.1.243_clang8.0.1.cmake -DCMAKE_INSTALL_PREFIX=../install_dir/ -DCMAKE_BUILD_TYPE=Debug
```

I've also provided the gdb backtrace full for this problem, and it appears to at least be crashing on the TestFuser.OneMillionSmallKernels problem.

```
#0  0x0000000010013c8c in LoopFuser::registerAction<__nv_dl_wrapper_t<__nv_dl_tag<void (*)(), &(cuda_test_X_OneMillionSmallFusedKernels()), 2u>, int, int, int, care::host_device_ptr<int>, int, care::host_device_ptr<int> >, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), &(cuda_test_X_OneMillionSmallFusedKernels()), 1u>> >(int, int, int&, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), &(cuda_test_X_OneMillionSmallFusedKernels()), 1u>>&&, __nv_dl_wrapper_t<__nv_dl_tag<void (*)(), &(cuda_test_X_OneMillionSmallFusedKernels()), 2u>, int, int, int, care::host_device_ptr<int>, int, care::host_device_ptr<int> >&&, int, int&, care::host_device_ptr<int>) (this=0x132df850, 
    start=0, end=32, start_pos=@0x7fffffffc0bc: 0, 
    conditional=<unknown type in CARE/build/bin/Benchmarks, CU 0x0, DIE 0x3b682>, 
    action=<unknown type in CARE/build/bin/Benchmarks, CU 0x0, DIE 0x3b692>, scan_type=0, pos_store=@0x10431358: 0, counts_to_offsets_scanvar=...)
    at CARE/src/care/LoopFuser.h:955
        lambda_size = 136
        conditional_size = 8
#1  0x000000001001024c in cuda_test_X_OneMillionSmallFusedKernels ()
    at CARE/test/Benchmarks.cpp:101
        __fuser__ = 0x132df850
        __fusible_offset__ = 327648
        __fusible_end_index__ = 32
        __fusible_scan_pos__ = 0
        __fusible_start_index__ = 0
        i = 10239
        __phase_observer = 0x132eae10
        numLoops = 1000000
        loopLength = 32
        a = {<chai::ManagedArray<int>> = {<chai::CHAICopyable> = {<No data fields>}, 
            m_active_pointer = 0x130f44c0, m_active_base_pointer = 0x130f44c0, 
            m_resource_manager = 0x10432778 <chai::ArrayManager::getInstance()::s_resource_manager_instance>, 
            m_elems = 32, m_offset = 0, m_pointer_record = 0x130f4570, m_is_slice = false}, <No data fields>}
        b = {<chai::ManagedArray<int>> = {<chai::CHAICopyable> = {<No data fields>}, 
            m_active_pointer = 0x130f4620, m_active_base_pointer = 0x130f4620, 
            m_resource_manager = 0x10432778 <chai::ArrayManager::getInstance()::s_resource_manager_instance>, 
            m_elems = 32, m_offset = 0, m_pointer_record = 0x130b4670, m_is_slice = false}, <No data fields>}
#2  0x000000001000fe8c in TestFuser_OneMillionSmallFusedKernels_Test::TestBody (this=0x10443060)
    at CARE/test/Benchmarks.cpp:92
No locals.
#3  0x0000000010095174 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (
    object=0x10443060, method=&virtual testing::Test::TestBody(), location=0x101f96e8 "the test body")
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2555
No locals.
#4  0x0000000010071330 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (
    object=0x10443060, method=&virtual testing::Test::TestBody(), location=0x101f96e8 "the test body")
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2591
        e = @0x7fffffffc380: warning: can't find linker symbol for virtual table for `std::exception' value
warning:   found `testing::TestResult::Skipped() const' instead
{_vptr.exception = 0x1004f2bc <testing::TestResult::Skipped() const+92>}
#5  0x000000001005054c in testing::Test::Run (this=0x10443060)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2630
        impl = 0x10440230
#6  0x0000000010051510 in testing::TestInfo::Run (this=0x10440970)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2807
        impl = 0x10440230
        repeater = 0x10440460
        start = 1604098798174
        test = 0x10443060
#7  0x0000000010051ecc in testing::TestSuite::Run (this=0x10440620)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2939
        i = 2
        impl = 0x10440230
        repeater = 0x10440460
#8  0x00000000100606d0 in testing::internal::UnitTestImpl::RunAllTests (this=0x10440230)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:5480
test_index = 0
        start = 1604098778744
        i = 0
        gtest_is_initialized_before_run_all_tests = true
        in_subprocess_for_death_test = false
        should_shard = false
        has_tests_to_run = true
        failed = false
        repeater = 0x10440460
        repeat = 1
        gtest_repeat_forever = false
#9  0x000000001009b614 in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x10440230, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x10060190 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x101f9f6b "auxiliary test code (environments or event listeners)")
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2555
No locals.
#10 0x0000000010074ec0 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x10440230, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x10060190 <testing::internal::UnitTestImpl::RunAllTests()>, 
    location=0x101f9f6b "auxiliary test code (environments or event listeners)")
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:2591
        e = @0x7fffffffc8e0: {_vptr.exception = 0x7fffffffc9c0}
#11 0x0000000010060114 in testing::UnitTest::Run (
    this=0x104311e0 <testing::UnitTest::GetInstance()::instance>)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest.cc:5067
        in_death_test_child_process = false
        premature_exit_file = {premature_exit_filepath_ = {static npos = <optimized out>, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x2000002e7c80 <std::string::_Rep::_S_empty_rep_storage+24> ""}}}
#12 0x0000000010042628 in RUN_ALL_TESTS ()
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/include/gtest/gtest.h:2470
No locals.
#13 0x00000000100425cc in main (argc=1, argv=0x7fffffffceb8)
    at CARE/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc:52
```

**Comment by adayton1** [comment]
Fixed by PR #87
